site:
  title: MuleSoft Documentation
  url: https://docs-new.stgx.mulesoft.com
  start_page: general::index.adoc
content:
  sources:
    - url: git@github.com:mulesoft/docs-access-management
    - url: git@github.com:mulesoft/docs-mule-sdk
      branches: [v1.0, v1.1]
    - url: git@github.com:mulesoft/docs-general
    - url: git@github.com:mulesoft/docs-munit
      branches: [v2.1, v1.3]
    - url: git@github.com:mulesoft/docs-object-store
    - url: git@github.com:mulesoft/docs-partner-manager
    - url: git@github.com:mulesoft/docs-private-cloud
    - url: git@github.com:mulesoft/docs-release-notes
    - url: git@github.com:mulesoft/docs-runtime-manager
    - url: git@github.com:mulesoft/docs-studio

ui:
  bundle:
    url: https://codeload.github.com/mulesoft/docs-site-antora-ui/zip/master?token=AP_JEkXyW5cW0-TJQEGWdGqQtL39ZAkzks5bgBc6wA==
    snapshot: true
