= MuleSoft Docs: NGINX Configuration
:uri-nginx: http://nginx.org
:uri-proxy-pass: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass

This directory contains the NGINX web server configuration for the MuleSoft documentation site.

The web server used for the site is {uri-nginx}[NGINX].
Files are hosted in an S3 bucket.
After performing some $uri cleaning and rewrites, NGINX forwards the request to the S3 bucket to retrieve the file using the {uri-proxy-pass}[proxy_pass] directive.
As a result, NGINX does not access files from the local disk.

== Files

This directory contains three files:

link:nginx.conf[]::
Provides the necessary fragments for the core web server configuration.
These fragments must be integrated directly into [.path]_/etc/nginx/nginx.conf_.
This file does not itself contain the complete NGINX server configuration.
Rather, it's provies a replacement for all existing `location` blocks inside the `server` block in [.path]_/etc/nginx/nginx.conf_.

link:includes/s3-proxy.conf[]::
Provides the shared settings for interacting with the S3 bucket.
Most of the directives focus on hiding headers sent by S3 and configures NGINX to handle error responses.

link:includes/rewrites.conf[]::
Provides all the redirects for the files and directories in the docs site.
It preserves rewrites from the old site and defines redirects from the versionless component root to the latest version for each versioned component.

== Prequisites and Notes

The public must have the ability to list files in the S3 bucket.
Otherwise, S3 will send a 403 code instead of a 404 code when a file cannot be found.

S3 will automatically look for an index.html file inside the folder if the folder does not resolve to a key in the bucket.
S3 does this by issuing a 302 redirect with the trailing slash appended.
// if the files have a common prefix, this prefix must be stripped from the redirect URL, which is handled in s3-proxy.conf

NOTE: The NGINX `try_files` directive doesn't work with S3 proxy pass.

The error page in S3 should be configured as [.path]_404.html_.

== Refreshing the Rewrites

When the site is publish, the [.path]_etc/nginx/includes/rewrites.conf_ gets written to the file [path]_.rewrites.conf_ at the root of the S3 bucket.
This file needs to be picked up and moved to the location [.path]_/etc/nginx/includes/rewrites.conf_ on the web server on a recurring basis.

== Redirect Scenarios

The provided configuration covers the following scenarios, listed in the order in which they are processed.

[cols="2,2,1"]
|===
|From $uri | To $uri | Method

|/studio
|/studio/
|301

|/index.html
|/
|301

|/index
|/
|301

|/munit/1.3/index.html
|/munit/1.3/
|301

|/munit/1.3/index
|/munit/1.3/
|301

|/mule-runtime/3.8/mule-concepts.html
|/mule-runtime/3.8/mule-concepts
|301

|/mule-runtime/3.8/_images/flows.png
|/mule-runtime/3.8/_images/flows.png
|200

|/anypoint-studio/v/6
|/studio/6
|301

|/anypoint-studio/v/6/
|/studio/6/
|301

|/anypoint-studio/v/6/basic-studio-tutorial
|/anypoint-studio/6/basic-studio-tutorial
|301

|/anypoint-studio/
|/studio/
|301

|/anypoint-studio/6/basic-studio-tutorial
|/studio/6/basic-studio-tutorial
|301

|/studio/
|/studio/6/
|302

// QUESTION which rule does this??
|/studio/6
|/studio/6/
|302

|/studio/6/
|/studio/6/index.html
|S3 internal

|/studio/6/basic-studio-tutorial
|/studio/6/basic-studio-tutorial.html
|S3 internal
|===

== Resources

* https://medium.com/@willmorgan/moving-a-static-website-to-aws-s3-cloudfront-with-https-1fdd95563106
* https://www.digitalocean.com/community/tutorials/understanding-nginx-server-and-location-block-selection-algorithms
